# 行列演算の基礎

$$ w = (X^TX)^{-1}X^Ty $$

♦必要な知識<br>
・ベクトルの定義<br>
・行列の定義<br>
・転地<br>
・逆行列<br>
・行列積<br>

In [1]:
import numpy as np

In [2]:
# ベクトルの定義
x = np.array(([1],[2],[3]))
x

array([[1],
       [2],
       [3]])

In [3]:
x.shape

(3, 1)

In [4]:
# 行列の定義
X = np.array(([1,2],[3,4]))
X

array([[1, 2],
       [3, 4]])

In [5]:
#転置(Transpose)
Xt = X.T

In [6]:
#逆行列(linlog : linear Algebra : 線形代数)
X_inv = np.linalg.inv(X)
X_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [7]:
# 行列積
XX_inv = np.dot(X,X_inv)
XX_inv

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [8]:
## Numpyでよく使う処理
B = np.array([
    [1,2,3],
    [2,3,4]
])

In [9]:
B.shape

(2, 3)

In [10]:
row,col = B.shape
print(row,col)

2 3


In [11]:
for b in B:
    print(b)
    print("-------")

[1 2 3]
-------
[2 3 4]
-------


# 演習問題
## 重回帰分析の計算

♦ データセット
$$
X = 
	\begin{bmatrix}
   1 & 2 & 3\\
   1 & 2 & 5\\
   1 & 3 & 4\\
   1 & 5 & 9
\end{bmatrix}
, y = 
	\begin{bmatrix}
   1\\
   5\\
   6\\
   8
\end{bmatrix}
$$

♦ 必要な知識
$$ w = (X^TX)^{-1}X^Ty $$
ベクトルの定義<br>
行列の定義<br>
転置<br>
逆行列<br>
行列積<br>

♦ 流れ

1. ステップ1;$$X^TX$$
1. ステップ2:$$(X^TX)^{-1}$$
1. ステップ3:$$X^Ty$$
1. ステップ4:$$ w = (X^TX)^{-1}X^Ty $$

In [12]:
import numpy as np

In [13]:
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]
])

In [30]:
y = np.array([
    [1],
    [5],
    [6],
    [8]])
y

array([[1],
       [5],
       [6],
       [8]])

In [15]:
# Step1
XtX = np.dot(X.T,X)
XtX

array([[  4,  12,  21],
       [ 12,  42,  73],
       [ 21,  73, 131]])

In [16]:
# Step2
XtX_inv = np.linalg.inv(XtX)
XtX_inv

array([[ 1.76530612, -0.39795918, -0.06122449],
       [-0.39795918,  0.84693878, -0.40816327],
       [-0.06122449, -0.40816327,  0.24489796]])

In [21]:
#step3
Xty = np.dot(X.T , y)
Xty

array([[ 20],
       [ 70],
       [124]])

In [22]:
#Step4
w = np.dot(XtX_inv,Xty)
w

array([[-0.14285714],
       [ 0.71428571],
       [ 0.57142857]])

# 重回帰分析の計算

♦ データセット
$$
X = 
	\begin{bmatrix}
   1 & 2 & 3\\
   1 & 2 & 5\\
   1 & 3 & 4\\
   1 & 5 & 9
\end{bmatrix}
, y = 
	\begin{bmatrix}
   1\\
   5\\
   6\\
   8
\end{bmatrix}
$$

♦ scikit-learn<br>
▼ [公式ドキュメント](https://scikit-learn.org/stable/)

In [25]:
import sklearn
sklearn.__version__

'1.3.1'

In [28]:
import numpy as np

In [32]:
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]
])
X

array([[1, 2, 3],
       [1, 2, 5],
       [1, 3, 4],
       [1, 5, 9]])

In [33]:
y = np.array([
    [1],
    [5],
    [6],
    [8]])
y

array([[1],
       [5],
       [6],
       [8]])

## scikit-learnで実装
[Webページ](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html)

In [35]:
from sklearn.linear_model import LinearRegression

In [37]:
model = LinearRegression()

In [39]:
#モデルの学習　←　パラメーターの調整
model.fit(X,y)

LinearRegression()

In [43]:
#調整後のパラメータの確認
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [45]:
model = LinearRegression()
model.fit(X,y)
model.coef_

array([[0.        , 0.71428571, 0.57142857]])

In [44]:
model = LinearRegression(fit_intercept=False)
model.fit(X,y)
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [47]:
model.score(X,y)

0.6923076923076922

In [49]:
x_new = np.array([[1,3,6]])
x_new

array([[1, 3, 6]])

In [50]:
y_pred = model.predict(x_new)
y_pred

array([[5.42857143]])